apiVersion: v1
kind: Secret
metadata:
  name: mysql-ventas-secret
  namespace: innovatech
type: Opaque
stringData:
  MYSQL_DATABASE: ventasdb
  MYSQL_USER: ventasuser
  MYSQL_PASSWORD: ventaspass
  MYSQL_ROOT_PASSWORD: rootpass