apiVersion: v1
kind: Secret
metadata:
  name: mysql-ventas-secret
  namespace: innovatech
type: Opaque
stringData:
  MYSQL_DATABASE: ventasdb
  MYSQL_USER: REEMPLAZAR
  MYSQL_PASSWORD: REEMPLAZAR
  MYSQL_ROOT_PASSWORD: REEMPLAZAR
