apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ventas
  namespace: innovatech
spec:
  serviceName: mysql-ventas
  replicas: 1
  selector:
    matchLabels:
      app: mysql-ventas
  template:
    metadata:
      labels:
        app: mysql-ventas
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mysql-ventas
          image: mysql:8.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-ventas-secret
          volumeMounts:
            - name: mysql-ventas-data
              mountPath: /var/lib/mysql
          startupProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD --silent"]
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD --silent"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD --silent"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
  volumeClaimTemplates:
    - metadata:
        name: mysql-ventas-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
