apiVersion: v1
kind: Service
metadata:
  name: mysql-ventas
  namespace: innovatech
spec:
  clusterIP: None
  selector:
    app: mysql-ventas
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
